sudo: required
services:
  - docker

before_install:
  - docker build -t jurisbandenieks/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jurisbandenieks/docker-react npm run test

language: generic

deploy:
  provider: elasticbeanstalk
  region: "eu-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-south-1-949370492564"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
